### ISSUE TITLE
SciDB 14.8

### ISSUE THREAD

**Issue by albhasan** [Paradigm4/r_exec#1]
Good afternoon! - I compiled the r_exec plugin but it mismatches SciDB. Is r_exec no longer supported? 

Kind regards.

load_library('r_exec');
SystemException in file: src/util/PluginManager.cpp function: findModule line: 130
Error id: scidb::SCIDB_SE_PLUGIN_MGR::SCIDB_LE_WRONG_MODULE_VERSION
Error description: Plugin manager error. Plugin version does not match the version of SciDB. The plugin r_exec has version 13.9.0.0 but SciDB version is 14.8.0.7978.

**Comment by albhasan** [comment]
Good afternoon. We are migrating to SciDB 15.7; however, some users still need R_exec. Is R_exec mean to run on 15.7? Thanks!

**Comment by bwlewis** [comment]
Not really. The code in this repository is not being worked on by me. We have in mind re-visiting this idea from the ground up with a different implementation, something more general and more similar to the Hadoop streaming interface most likely. Feel free to hack on this and use it as you see fit.

**Comment by albhasan** [comment]
Thank you very much!
